name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up fake SMTP server
      run: docker run -p 3000:80 -p 2525:25 -d rnwood/smtp4dev:v3

    - name: Build
      run: dotnet build
    
    - name: Test
      env:
        Exchange_User_Password: ${{ secrets.EXCHANGE_USER_PASSWORD }}
        Exchange_Application_ID: ${{ secrets.EXCHANGE_APPLICATION_ID }}
        Exchange_Tenant_ID: ${{ secrets.EXCHANGE_TENANT_ID }}
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push Frends.Community.Email/bin/Release/Frends.Community.Email.*.nupkg  --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community-test/api/v2/package --symbol-source https://www.myget.org/F/frends-community-test/symbols/api/v2/package
